[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "oxpy"
version = "@OXPY_VERSION@"
description = "A code primarily aimed at DNA and RNA coarse-grained simulations"
readme = "README.md"
authors = [
    {name = "Lorenzo Rovigatti", email = "lorenzo.rovigatti@uniroma1.it"},
    {name = "Flavio Romano", email = "flavio.romano@unive.it"},
    {name = "Petr Å ulc", email = "psulc@asu.edu"}
]
license =  { "text" = "GPL-3.0-or-later" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: C++",
    "Topic :: Scientific/Engineering :: Physics"
]

[project.urls]
homepage = "https://github.com/lorenzo-rovigatti/oxDNA"

[tool.setuptools.package-data]
oxpy = ["*.so"]
