base_dir = "base"
A = 2.0
sigma = 0.2
tau = 10000
dX = 0.01
N_walkers = 4
T = "35C"
dT = 10.0
dim = 1
p_fname = "locs.meta"
ratio = false
angle = false
coordination = true
Niter = 20000
xmin = 0.0
xmax = 7.0
conf_interval = 1000
save_hills = 100
continue_run = false
use_sequential_GPUs = false
op_interval = 1000
