# Builds using pip and tests using pytest

name: OAT Linux

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.13"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools pytest cython
        
    - name: Install oat
      run: |
        python -m pip install ./analysis
        
    - name: Check config
      run: |
        oat config

    - name: Run pytest
      run: |
        pytest ./analysis/tests/test_cli/
        
    - name: Uninstall oat
      run: |
        pip uninstall oxDNA_analysis_tools -y