# Builds using pip and tests using pytest

name: OAT/oxpy Linux

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.13"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools pytest cython

    - name: Build
      run: |
        mkdir build
        pushd build
        cmake .. -DPython=1 -DOxpySystemInstall=1
        make -j2   
        make install
        popd 

    - name: Check import from Command Line
      run: |
        python -c 'import oxpy; import oxDNA_analysis_tools'

    - name: Check oxpy
      run: |
        pushd examples/OXPY
        python run.py
        popd
        
    - name: Check config
      run: |
        oat config

    - name: Run pytest
      run: |
        pytest ./analysis/tests/test_cli/
        
    - name: Uninstall oat
      run: |
        pip uninstall oxDNA_analysis_tools -y

    - name: Uninstall oxpy
      run: |
        pip uninstall oxpy -y