# Builds using pip and tests using pytest

name: OxPy Linux

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install numpy
        
    - name: Install oxpy
      run: |
        python -m pip install .
        
    - name: Check import from Command Line
      run: |
        mkdir test-folder && pushd test-folder
        python -c 'import oxpy'
        
    - name: Uninstall oxpy
      run: |
        pip uninstall oxpy -y
