# Builds using pip and tests using pytest

name: OxPy Linux

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pybind11
    - name: Build oxDNA and install oxpy
      run: |
        mkdir build && pushd build
        cmake .. -DCUDA=0 -DPython=1
        make -j2
        pip install build/lib/oxpy
        popd
    - name: Check import from Command Line
      run: |
        mkdir test-folder && pushd test-folder
        python -c 'import oxpy'

