# Runs the quick_input tests of oxDNA
# Only used on pull requests

name: Linux CPU Testing Quick Input

on: 
  pull_request:
    branches: [master, rovigatti]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        mkdir build
        pushd build
        cmake .. -DCUDA=0
        make -j2
        popd
    - name: Run Simple Test Script
      run: |
        pushd build
        make test_quick
